### ISSUE TITLE
[BUG] I cant run grpc server

### ISSUE THREAD

**Issue by revilon1991** [spiral/roadrunner-plugins#100]
Thank you for your work. I have a problem. Maybe, it isn't a bug, but I seem this kind of issue more matches my problem.

I got the `rr` by documentation, then I ran `rr` but I didn't see that `grpc` server is running.
And my client code can't connect to `grpc` server.
What's wrong?

I tried this code:

```shell
composer require spiral/roadrunner:v2.0 nyholm/psr7
./vendor/bin/rr get-binary
./rr serve
# DEBUG rpc Started RPC service {"address": "tcp://127.0.0.1:6001", "plugins": ["informer", "resetter"]}
```

I expected to see this happen:
```json
{"address": "tcp://127.0.0.1:6001", "plugins": ["informer", "resetter", "grpc"]}
```

Instead, this happened:
```json
{"address": "tcp://127.0.0.1:6001", "plugins": ["informer", "resetter"]}
```

The **version of RR** used: `v2.5.3`

The **operation system** used: `linux`

RR configuration file content:

```yaml
# .rr.yaml
rpc:
  enable: true
  listen: tcp://127.0.0.1:6001

grpc:
  listen: "tcp://:9090"
  proto: "service.proto"
  tls:
    key:  "server.key"
    cert: "server.crt"
  workers:
    command: "php GrpcWorker.php"
    pool:
      numWorkers: 1
```

My worker for `grpc` server:
```php
// GrpcWorker.php
<?php

/**
 * Sample GRPC PHP server.
 */

use Service\EchoInterface;
use Spiral\RoadRunner\GRPC\Server;
use Spiral\RoadRunner\Worker;

require __DIR__ . '/vendor/autoload.php';

$server = new Server(null, [
    'debug' => true,
]);

$server->registerService(EchoInterface::class, new EchoService());

$server->serve(Worker::create());
```

My client code:
```php
<?php

include "vendor/autoload.php";

$client = new \Service\EchoClient(
    'localhost:9090',
    [
        'credentials' => \Grpc\ChannelCredentials::createSsl(file_get_contents("server.crt")),
    ]
);

$result = $client->Ping(
    new \Service\Message()
)->wait();

var_dump($result[1]->code, $result[1]->details);
// int(14)
// string(34) "failed to connect to all addresses"
```

Errortrace, Backtrace or Panictrace:
none

**Comment by rustatian** [comment]
Hey @revilon1991 . Documentation is located here: https://github.com/spiral/roadrunner-docs/blob/master/beep-beep/grpc.md
You used the wrong configuration (from RR1). There is no `workers` configuration section. Please, use the configuration from the link above.

**Comment by rustatian** [comment]
This is the correct output: `{"address": "tcp://127.0.0.1:6001", "plugins": ["informer", "resetter"]}`
This output is from the RPC plugin with registered RPC endpoints. GRPC plugin doesn't have any RPC endpoints, thus, didn't appear in this log message.

**Comment by revilon1991** [comment]
@rustatian yes, I saw this doc.
So, I changed my `.rr.yaml`:
```yaml
grpc:
  listen: "tcp://localhost:9001"
  proto: "service.proto"
  tls:
    key: "server.crt"
    cert: "server.key"
    client_auth_type: "no_client_certs"

  max_send_msg_size: 50
  max_recv_msg_size: 50
  max_connection_idle: 0s
  max_connection_age: 0s
  max_connection_age_grace: 0s
  max_concurrent_streams: 10
  ping_time: 1s
  timeout: 200s

  pool:
    num_workers: 2
    max_jobs: 0
    allocate_timeout: 60s
    destroy_timeout: 60
```
but I got a connection error from the client again.

Maybe we have something else?

I would be glad if I can debug that.

**Comment by rustatian** [comment]
> but I got a connection error from the client again.

Could you please share this error?

**Comment by revilon1991** [comment]
Yes. My client code:
```php
<?php

include "vendor/autoload.php";

$client = new \Service\EchoClient(
    'localhost:9090',
    [
        'credentials' => \Grpc\ChannelCredentials::createSsl(file_get_contents("server.crt")),
    ]
);

$result = $client->Ping(
    new \Service\Message()
)->wait();

var_dump($result[1]->code, $result[1]->details);
```
and I get:
```
// int(14)
// string(34) "failed to connect to all addresses"
```

Also I checked with `nmap` what's port is open when the server is running.
```
# nmap localhost -p9001
PORT     STATE  SERVICE
9001/tcp closed tor-orport
```

I guess that directive `grpc` not handled because I tried to change keys to a wrong (for ex `listen` => `lusten`) and it doesn't give effect (I didn't see any error).

**Comment by rustatian** [comment]
Could you please share your full configuration? (rr.yaml)

**Comment by revilon1991** [comment]
yes, of course. `cat .rr.yaml`
=>
```yaml
rpc:
  enable: true
  listen: tcp://127.0.0.1:6001

grpc:
  lusten: "tcp://localhost:9001"
  workers.command: "php GrpcWorker.php"
  proto: "service.proto"
  tls:
    key: "server.crt"
    cert: "server.key"
    client_auth_type: "no_client_certs"

  max_send_msg_size: 50
  max_recv_msg_size: 50
  max_connection_idle: 0s
  max_connection_age: 0s
  max_connection_age_grace: 0s
  max_concurrent_streams: 10
  ping_time: 1s
  timeout: 200s

  pool:
    num_workers: 2
    max_jobs: 0
    allocate_timeout: 60s
    destroy_timeout: 60
```

**Comment by rustatian** [comment]
@revilon1991 Where did you find this option: `workers.command: "php GrpcWorker.php"` ?

**Comment by revilon1991** [comment]
I saw this here https://github.com/spiral/app-grpc#running-grpc-server

It's all my tries.
Also, I tried like that:
```yaml
rpc:
  enable: true
  listen: tcp://127.0.0.1:6001

grpc:
  listen: "tcp://localhost:9001"
#  workers.command: "php GrpcWorker.php"
  proto: "service.proto"
  tls:
    key: "server.crt"
    cert: "server.key"
    client_auth_type: "no_client_certs"

  max_send_msg_size: 50
  max_recv_msg_size: 50
  max_connection_idle: 0s
  max_connection_age: 0s
  max_connection_age_grace: 0s
  max_concurrent_streams: 10
  ping_time: 1s
  timeout: 200s

  pool:
    num_workers: 2
    max_jobs: 0
    allocate_timeout: 60s
    destroy_timeout: 60
```
no difference :(

**Comment by rustatian** [comment]
You used RRv1 configuration on the RRv2 binary (I mentioned this).
1. `grpc` configuration is correct.
2. `rpc` doesn't have `enable` option.
3. https://github.com/spiral/roadrunner-plugins/blob/master/tests/plugins/grpc/configs/.rr-grpc-init.yaml sample config (attention at the `server` plugin)

**Comment by revilon1991** [comment]
You are right.
I have progress, but now I see error about CRC:
```
# ./rr serve
handle_serve_command: Serve error:
        endure_start:
        endure_serve_internal: Function call error:
        endure_call_serve_fn: got initial serve error from the Vertex grpc.Plugin, stopping execution, error: grpc_plugin_serve: WorkerAllocate:
        goridge_frame_receive: CRC verification failed
```
Though I copied config from example.

Do I have to do somthing else?

**Comment by rustatian** [comment]
This is the sample worker: https://github.com/spiral/roadrunner-plugins/blob/master/tests/worker-grpc.php
CRC error means, that your worker responded incorrectly.

**Comment by rustatian** [comment]
Keep in mind, that you should use the new package: https://github.com/spiral/roadrunner-grpc

**Comment by revilon1991** [comment]
Yes, I use the package `spiral/roadrunner-grpc` and content of my worker is identical with https://github.com/spiral/roadrunner-plugins/blob/master/tests/worker-grpc.php

I can show it:
`# cat GrpcWorker.php`
```php
<?php

/**
 * Sample GRPC PHP server.
 */

use Service\EchoInterface;
use Spiral\RoadRunner\GRPC\Server;
use Spiral\RoadRunner\Worker;

require __DIR__ . '/vendor/autoload.php';

$server = new Server(null, [
    'debug' => false, // optional (default: false)
]);

$server->registerService(EchoInterface::class, new EchoService());

$server->serve(Worker::create());
```

**Comment by rustatian** [comment]
The problem might be in some PHP warnings before RR starts for example.

**Comment by revilon1991** [comment]
Yes. I saw it when I launch `php GrpcWorker.php`
```
Fatal error: Uncaught Error: Class "EchoService" not found in /app/GrpcWorker.php:17
Stack trace:
#0 {main}
  thrown in /app/GrpcWorker.php on line 17
```
I should copy the example files to the project namespace and use those in the worker. 

Now I have a strange problem with the port.
```
handle_serve_command: Serve error:
        endure_start:
        endure_serve_internal: Function call error:
        endure_call_serve_fn: got initial serve error from the Vertex grpc.Plugin, stopping execution, error: grpc_plugin_serve: cannot bind to "localhost:9001": cannot assign requested address
```

But my port 9001 is not busy. I checked it with `nmap` utils and I tried other ports.

If I can increase verbose maybe I will be able to repair it.

**Comment by rustatian** [comment]
@revilon1991 Yes, you can use:
```yaml
logs:
  mode: development
  level: debug
```
ref: https://github.com/spiral/roadrunner-binary/blob/master/.rr.yaml#L57

**Comment by revilon1991** [comment]
I add this to my config:
```yaml
logs:
      mode: development
      level: debug
      output: /var/log/rr_errors.log
```

It got me such little... :(
```
/app # ./rr serve
/app # cat /var/log/rr_errors.log 
2021-10-31T17:12:37.547Z        DEBUG   server          worker constructed      {"pid": 1491}
2021-10-31T17:12:37.594Z        DEBUG   server          worker constructed      {"pid": 1495}
```

**Comment by rustatian** [comment]
That means, that workers started successfully.

**Comment by revilon1991** [comment]
It starts and stops at once...
I can show you my full flow work:
![road runner cant start](https://screenshots.9ek.ru/s/Снимок_экрана_2021-10-31_в_19.17.54.png)

**Comment by rustatian** [comment]
The RR clearly says that it cannot bind to this address. Check the RR permissions or other running software.

**Comment by revilon1991** [comment]
I could resolve this problem.
I just changed the directive listen:
```yaml
# ...
grpc:
    listen: "tcp://localhost:9001"
# ...
```
=>
```yaml
# ...
grpc:
    listen: "tcp://:9001"
# ...
```

Now it works.

Thank you so much @rustatian. 🤗
I'm very glad.
