### ISSUE TITLE
[BUG] [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xd7d84e]

### ISSUE THREAD

**Issue by brzuchal** [spiral/roadrunner-plugins#155]
Not much to say, it happens on reloading workers.

The version of RR used: *version: 2.6.3, buildtime: 2021-12-03T11:37:00+0000*
  
My `.rr.yaml` configuration is:
```yaml
server:
    command: "php bin/console baldinof:roadrunner:worker"
    env:
        - APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime
http:
    address: 0.0.0.0:3000
    uploads:
        forbid: [ ".php", ".exe", ".bat" ]
    headers:
        cors:
            allowed_origin: "*"
            allowed_headers: "*"
            allowed_methods: "GET,POST,PUT,DELETE"
            allow_credentials: false
            exposed_headers: "Cache-Control,Content-Type"
logs:
    mode: development
    channels:
        http:
            level: info
        server:
            level: info
            mode: raw
reload:
    enabled: true
    interval: 1s
    patterns: [".php", ".yaml"]
    services:
        http:
            dirs: ["."]
            recursive: true
status:
    address: localhost:3001
rpc:
    listen: tcp://127.0.0.1:6001
```

Errortrace, Backtrace or Panictrace
```
app_1  | 2021-12-07T08:38:20.105Z       DEBUG   reload          file was updated        {"path": "/app/var/cache/prod/App_KernelProdDebugContainer.php.lock", "name": "App_KernelProdDebugContainer.php.lock", "size": 0}
app_1  | 2021-12-07T08:38:21.106Z       INFO    http            HTTP plugin got restart request. Restarting...
app_1  | panic: runtime error: invalid memory address or nil pointer dereference
app_1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xd7d84e]
app_1  | 
app_1  | goroutine 65 [running]:
app_1  | github.com/spiral/roadrunner-plugins/v2/http.(*Plugin).Reset(0xc00012ed10)
app_1  |        github.com/spiral/roadrunner-plugins/v2@v2.6.3/http/plugin.go:358 +0xee
app_1  | github.com/spiral/roadrunner-plugins/v2/resetter.(*Plugin).Reset(0xc000ae0e30, {0xc000221bf0, 0x4})
app_1  |        github.com/spiral/roadrunner-plugins/v2@v2.6.3/resetter/plugin.go:27 +0x142
app_1  | github.com/spiral/roadrunner-plugins/v2/reload.(*Plugin).Serve.func2()
app_1  |        github.com/spiral/roadrunner-plugins/v2@v2.6.3/reload/plugin.go:129 +0x2ee
app_1  | created by github.com/spiral/roadrunner-plugins/v2/reload.(*Plugin).Serve
app_1  |        github.com/spiral/roadrunner-plugins/v2@v2.6.3/reload/plugin.go:113 +0x27d
```

</p>
</details>
