### ISSUE TITLE
[💡 FEATURE REQUEST]: Decouple Application Logging and Roadrunner Logging

### ISSUE THREAD

**Issue by Bibob7** [spiral/roadrunner-plugins#176]
### Plugin

Server

### I have an idea!

I have a problem when using Application logging since it is currently coupled to the logs config of the server plugin.
I can only see application logs, when log level of roadrunner is at least `info`

Additionally, also the log encoding influences my application logging, where I already use a json formatter with monolog.

I would like to simply write application logs untouched to stderr.

In the server plugin folder, I found in oninit.go:

```
func (p *Plugin) Write(data []byte) (int, error) {
	p.log.Info(utils.AsString(data))
	return len(data), nil
}
```

Why not do something like this instead?:

```
func (p *Plugin) Write(data []byte) (int, error) {
	fmt.Print(utils.AsString(data))
	return len(data), nil
}

**Comment by rustatian** [comment]
Hey @Bibob7. You can simply use the `raw` log mode to write untouched logs -> https://github.com/spiral/roadrunner-binary/blob/master/.rr.yaml#L76

**Comment by rustatian** [comment]
So, your section for the `server` might be as the following (just for example):
```yaml
logs:
  # ----------------------- GENERAL LOG CONFIG FOR THE ALL PLUGINS
  mode: production
  level: error
  encoding: console
  line_ending: "\n"
  output: stderr
  err_output: stderr
  # ----------------------- GENERAL LOG CONFIG FOR THE ALL PLUGINS
  channels:
    # ---------------------- SPECIFIC CONFIGURATION FOR THE SERVER PLUGIN
    server:
      mode: raw
      level: info
      encoding: console
      output: stdout
      err_output: stderr
```

You can use such sections for any plugin.
