### ISSUE TITLE
[💡 FEATURE REQUEST]: Custom worker

### ISSUE THREAD

**Issue by Yurunsoft** [spiral/roadrunner-plugins#194]
### I have an idea!

I have an idea, listen to me!!

Can I customize the worker? Like HTTP, I can define commands, pools, etc

```yaml
rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php worker.php"

http:
  address: "0.0.0.0:8080"
  
worker:
  - name: myWorker
    command: "php my-worker.php"
    pool:
      num_workers: 4

logs:
  level: error
```

I hope to rely on the resident memory feature of roadrunner to implement my own worker.
