### ISSUE TITLE
[FEATURE REQUEST] Logs raw output without extra modification

### ISSUE THREAD

**Issue by butschster** [spiral/roadrunner-plugins#46]
I'm using the RR plugin `service` with Laravel console commands. From times to times I need to send logs from PHP to console.

When I run console  command without RR I have output like this.
![image](https://user-images.githubusercontent.com/773481/135140991-6ce2dd8a-4ada-4558-a7df-726e9d75be50.png)

But when I run the same command via RR  service plugin I have modified output, It has extra new lines and doesn't have colors
![image](https://user-images.githubusercontent.com/773481/135141214-7c8385b7-6a2d-404b-9d3e-2a7bcf57cc88.png)

It would be great to have ability to sent data from PHP to console without modification from the RR side.

P.S. I have the same problem with http worker also.

**RR config**
```yaml
rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php ./bin/rr-worker start"
  relay: pipes
  relay_timeout: "20s"

service:
  smtp:
    command: "php artisan smtp:start --host=0.0.0.0 --port=1025"
    process_num: 1
    exec_timeout: 0
    remain_after_exit: true
    restart_sec: 1

logs:
  level: info
  mode: raw
  output: stdout
```
