### ISSUE TITLE
[FEATURE REQUEST] More flexible static files serving

### ISSUE THREAD

**Issue by victor-sudakov** [spiral/roadrunner-plugins#50]
**Is your feature request related to a problem? Please describe.**
If I want to serve static files with different response headers, e.g. some files should have "Cache-Control: "public, max-age=300" and others "Cache-Control: no-cache" there seems no way to do it. 

**Describe the solution you'd like**
Could we have more than 1 static.dir with distinct "response" settings?

**Describe alternatives you've considered**
The only alternative is putting nginx in front of roadrunner which I don't particularly like.

**Additional context**
It would be also nice to be able to set the Expires header on static files, but it's probably another feature request already.

**Comment by victor-sudakov** [comment]
I'd suggest using a list to be more consistent with modern fashion:

```
http:
  static:             
    - path: "/www/images/"     
      response:       
        Cache-Control: "public, max-age=300"
    - path: "/www/js/"
      response:       
        Cache-Control: "no-cache"
```
