### ISSUE TITLE
[FEATURE REQUEST] Authorization plugin

### ISSUE THREAD

**Issue by OO00O0O** [spiral/roadrunner-plugins#55]
**Describe the solution you'd like**
For example: EMQX has multiple authorisation plugins - http, mysql, redis etc. Considering that a lot of people use RR for microservices with JWT, authorization could be moved to it too.

**Example config**
```yaml
auth:
    config: // this could be for each auth method, there for you can have multiple auth methods at once.
        header: Authorization
        query: token
        body: token
        timeout: 180 // ttl for cached authorization
    jwt: // does check jwt, append decoded info to attributes
        config:
            public: ...
    worker: ~ // send auth request over worker like Broadcast plugin does. Everything that workers returns is appended to user "session" and that data is appended to attributes in next request
    http: ~ // append headers etc and send further and wait for 2** response
    kv: ~ // key found and append its content to attributes
    sql:
        config:
            table: token
    passwd: ~
    list: ~ // basic auth
        config:
            hash: md5
        users:
            - username: SomeUser
              password: 5f4dcc3b5aa765d61d8327deb882cf99
      
       
```

For now only JWT makes sense. Example in practice: https://docs.emqx.io/en/broker/v4.3/advanced/auth.html#password-salting-rules-and-hash-methods

**Comment by rustatian** [comment]
Hey @OO00O0O , thanks for the FR.
I'm not quite sure, that I correctly understand your proposal. Could you please provide more details, especially about how other plugins will collaborate with the `auth` plugin and what data they should send to it? And full configuration, w/o `~`.
For example, what should be done for the `http` plugin (in terms of authorization), if the `auth` plugin exists?

**Comment by OO00O0O** [comment]
View of this functionality really depends on how you see RR in future and now. Me personally see it as http/ws application server/framework. I do not care about GRPC or Temporal. So I do not consider them in this example.

```
auth: // maybe this could be middleware for http
   config: // here we tell RR what http query/header(maybe body) parameters to use
       header: Authorization
       query: token
       authenticators: [jwt-auth, worker-auth] // executes in order
    jwt-auth:
        type: jwt
        public: ...
        fail: ignore
    worker-auth:
        type: worker
        ttl: 3600
        fail: deny
```

Flow: Client first time access service with expired JWT token in header `Authorization`
1.  RR sees used authorization header and takes its `value`
2. Because in `auth.config.authenticators` jwt-auth is first, it sends `value` to it.
3. jwt-auth sees that it's invalid query and there for returns `false`
4. Because `auth.jwt-auth.fail == ignore` it ignores failure and send further 
5. worker-auth uses same token to reauthorze. If it succeed it cashes return value with timeout
6. Now it attaches object to each http requests attributes. 

Main idea is, that RR should handle generic cases, so: au
