### ISSUE TITLE
[FEATURE REQUEST] Env variables for services

### ISSUE THREAD

**Issue by butschster** [spiral/roadrunner-plugins#60]
It would be great to have ability to set ENV variables for each service.

Something like this:

```yaml
monolog:
  command: "php artisan monolog:start --host=0.0.0.0 --port=9913"
  process_num: 1
  exec_timeout: 0
  restart_sec: 1
  line_ending: ""
  env:
    TERM_PROGRAM: Hyper
```
