### ISSUE TITLE
[BUG] RR2 GRPC reset

### ISSUE THREAD

**Issue by cappuc** [spiral/roadrunner-plugins#69]
I was testing the updated grpc plugin for rr v2 I found a problem with the reset.

The version of RR used: v2.5.0-beta.1

After calling reset command, subsequent requests returned this error in the logs:

```json
{
    "level": "info",
    "ts": 1633953748.839115,
    "logger": "grpc",
    "caller": "grpc/plugin.go:189",
    "msg": "method call finished with error",
    "error": "rpc error: code = Internal desc = static_pool_exec: Workers watcher stopped:\n\tstatic_pool_exec:\n\tworker_watcher_get_free_worker",
    "method": "/grpc.health.v1.Health/Check",
    "started": 1633953748.838041,
    "elapsed": 0.000668264
}

```

The config i used:

```yaml
rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php worker.php"

logs:
  mode: production
  level: debug
  output: stdout
  encoding: json

grpc:
  listen: tcp://127.0.0.1:9090
  proto: ./health.proto
```
